---
- name: Standard profile installation
  hosts: all

vars_files:
  - 01_softwarelist.vars

tasks:
  - name: Install software sequentially
    chocolatey.chocolatey.win_chocolatey:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop: "{{ choco_packages }}"
